//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("agsModel", "famfk", "FAMILIES", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WpfMvvmApplication1.Models.FAMILIES), "CHILDRENS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WpfMvvmApplication1.Models.CHILDRENS), true)]
[assembly: EdmRelationshipAttribute("agsModel", "cityfk", "CITIES", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WpfMvvmApplication1.Models.CITIES), "FAMILIES", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WpfMvvmApplication1.Models.FAMILIES), true)]
[assembly: EdmRelationshipAttribute("agsModel", "familyfk", "FAMILIES", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WpfMvvmApplication1.Models.FAMILIES), "FAMILYQUOTIENTS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WpfMvvmApplication1.Models.FAMILYQUOTIENTS), true)]

#endregion

namespace WpfMvvmApplication1.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class agsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new agsEntities object using the connection string found in the 'agsEntities' section of the application configuration file.
        /// </summary>
        public agsEntities() : base("name=agsEntities", "agsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new agsEntities object.
        /// </summary>
        public agsEntities(string connectionString) : base(connectionString, "agsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new agsEntities object.
        /// </summary>
        public agsEntities(EntityConnection connection) : base(connection, "agsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CHILDRENS> CHILDRENS
        {
            get
            {
                if ((_CHILDRENS == null))
                {
                    _CHILDRENS = base.CreateObjectSet<CHILDRENS>("CHILDRENS");
                }
                return _CHILDRENS;
            }
        }
        private ObjectSet<CHILDRENS> _CHILDRENS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CITIES> CITIES
        {
            get
            {
                if ((_CITIES == null))
                {
                    _CITIES = base.CreateObjectSet<CITIES>("CITIES");
                }
                return _CITIES;
            }
        }
        private ObjectSet<CITIES> _CITIES;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CIVILITIES> CIVILITIES
        {
            get
            {
                if ((_CIVILITIES == null))
                {
                    _CIVILITIES = base.CreateObjectSet<CIVILITIES>("CIVILITIES");
                }
                return _CIVILITIES;
            }
        }
        private ObjectSet<CIVILITIES> _CIVILITIES;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FAMILIES> FAMILIES
        {
            get
            {
                if ((_FAMILIES == null))
                {
                    _FAMILIES = base.CreateObjectSet<FAMILIES>("FAMILIES");
                }
                return _FAMILIES;
            }
        }
        private ObjectSet<FAMILIES> _FAMILIES;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FAMILYQUOTIENTS> FAMILYQUOTIENTS
        {
            get
            {
                if ((_FAMILYQUOTIENTS == null))
                {
                    _FAMILYQUOTIENTS = base.CreateObjectSet<FAMILYQUOTIENTS>("FAMILYQUOTIENTS");
                }
                return _FAMILYQUOTIENTS;
            }
        }
        private ObjectSet<FAMILYQUOTIENTS> _FAMILYQUOTIENTS;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MEDECINS> MEDECINS
        {
            get
            {
                if ((_MEDECINS == null))
                {
                    _MEDECINS = base.CreateObjectSet<MEDECINS>("MEDECINS");
                }
                return _MEDECINS;
            }
        }
        private ObjectSet<MEDECINS> _MEDECINS;

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="agsModel", Name="CHILDRENS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CHILDRENS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CHILDRENS object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static CHILDRENS CreateCHILDRENS(int id)
        {
            CHILDRENS cHILDRENS = new CHILDRENS();
            cHILDRENS.ID = id;
            return cHILDRENS;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string LASTNAME
        {
            get
            {
                return _LASTNAME;
            }
            set
            {
                OnLASTNAMEChanging(value);
                ReportPropertyChanging("LASTNAME");
                _LASTNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LASTNAME");
                OnLASTNAMEChanged();
            }
        }
        private string _LASTNAME;
        partial void OnLASTNAMEChanging(string value);
        partial void OnLASTNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string FIRSTNAME
        {
            get
            {
                return _FIRSTNAME;
            }
            set
            {
                OnFIRSTNAMEChanging(value);
                ReportPropertyChanging("FIRSTNAME");
                _FIRSTNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FIRSTNAME");
                OnFIRSTNAMEChanged();
            }
        }
        private string _FIRSTNAME;
        partial void OnFIRSTNAMEChanging(string value);
        partial void OnFIRSTNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<System.DateTime> BIRTHDATE
        {
            get
            {
                return _BIRTHDATE;
            }
            set
            {
                OnBIRTHDATEChanging(value);
                ReportPropertyChanging("BIRTHDATE");
                _BIRTHDATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BIRTHDATE");
                OnBIRTHDATEChanged();
            }
        }
        private Nullable<System.DateTime> _BIRTHDATE;
        partial void OnBIRTHDATEChanging(Nullable<System.DateTime> value);
        partial void OnBIRTHDATEChanged();
    
        ///// <summary>
        ///// No Metadata Documentation available.
        ///// </summary>
        //[EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        //[DataMemberAttribute()]
        //public Nullable<int> FAMILYID
        //{
        //    get
        //    {
        //        return _FAMILYID;
        //    }
        //    set
        //    {
        //        OnFAMILYIDChanging(value);
        //        ReportPropertyChanging("FAMILYID");
        //        _FAMILYID = StructuralObject.SetValidValue(value);
        //        ReportPropertyChanged("FAMILYID");
        //        OnFAMILYIDChanged();
        //    }
        //}
        //private Nullable<int> _FAMILYID;
        //partial void OnFAMILYIDChanging(Nullable<int> value);
        //partial void OnFAMILYIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> GENDERID
        {
            get
            {
                return _GENDERID;
            }
            set
            {
                OnGENDERIDChanging(value);
                ReportPropertyChanging("GENDERID");
                _GENDERID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GENDERID");
                OnGENDERIDChanged();
            }
        }
        private Nullable<int> _GENDERID;
        partial void OnGENDERIDChanging(Nullable<int> value);
        partial void OnGENDERIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<bool> EMT
        {
            get
            {
                return _EMT;
            }
            set
            {
                OnEMTChanging(value);
                ReportPropertyChanging("EMT");
                _EMT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EMT");
                OnEMTChanged();
            }
        }
        private Nullable<bool> _EMT;
        partial void OnEMTChanging(Nullable<bool> value);
        partial void OnEMTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<bool> HOSPITAL
        {
            get
            {
                return _HOSPITAL;
            }
            set
            {
                OnHOSPITALChanging(value);
                ReportPropertyChanging("HOSPITAL");
                _HOSPITAL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HOSPITAL");
                OnHOSPITALChanged();
            }
        }
        private Nullable<bool> _HOSPITAL;
        partial void OnHOSPITALChanging(Nullable<bool> value);
        partial void OnHOSPITALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<bool> CLINIC
        {
            get
            {
                return _CLINIC;
            }
            set
            {
                OnCLINICChanging(value);
                ReportPropertyChanging("CLINIC");
                _CLINIC = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CLINIC");
                OnCLINICChanged();
            }
        }
        private Nullable<bool> _CLINIC;
        partial void OnCLINICChanging(Nullable<bool> value);
        partial void OnCLINICChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> CLINICID
        {
            get
            {
                return _CLINICID;
            }
            set
            {
                OnCLINICIDChanging(value);
                ReportPropertyChanging("CLINICID");
                _CLINICID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CLINICID");
                OnCLINICIDChanged();
            }
        }
        private Nullable<int> _CLINICID;
        partial void OnCLINICIDChanging(Nullable<int> value);
        partial void OnCLINICIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<bool> BEPHOTOGRAPHY
        {
            get
            {
                return _BEPHOTOGRAPHY;
            }
            set
            {
                OnBEPHOTOGRAPHYChanging(value);
                ReportPropertyChanging("BEPHOTOGRAPHY");
                _BEPHOTOGRAPHY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BEPHOTOGRAPHY");
                OnBEPHOTOGRAPHYChanged();
            }
        }
        private Nullable<bool> _BEPHOTOGRAPHY;
        partial void OnBEPHOTOGRAPHYChanging(Nullable<bool> value);
        partial void OnBEPHOTOGRAPHYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<bool> PUBLICATIONPHOTOGRAPHY
        {
            get
            {
                return _PUBLICATIONPHOTOGRAPHY;
            }
            set
            {
                OnPUBLICATIONPHOTOGRAPHYChanging(value);
                ReportPropertyChanging("PUBLICATIONPHOTOGRAPHY");
                _PUBLICATIONPHOTOGRAPHY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PUBLICATIONPHOTOGRAPHY");
                OnPUBLICATIONPHOTOGRAPHYChanged();
            }
        }
        private Nullable<bool> _PUBLICATIONPHOTOGRAPHY;
        partial void OnPUBLICATIONPHOTOGRAPHYChanging(Nullable<bool> value);
        partial void OnPUBLICATIONPHOTOGRAPHYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<bool> OFFOUTPUTSSTRUCTURE
        {
            get
            {
                return _OFFOUTPUTSSTRUCTURE;
            }
            set
            {
                OnOFFOUTPUTSSTRUCTUREChanging(value);
                ReportPropertyChanging("OFFOUTPUTSSTRUCTURE");
                _OFFOUTPUTSSTRUCTURE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OFFOUTPUTSSTRUCTURE");
                OnOFFOUTPUTSSTRUCTUREChanged();
            }
        }
        private Nullable<bool> _OFFOUTPUTSSTRUCTURE;
        partial void OnOFFOUTPUTSSTRUCTUREChanging(Nullable<bool> value);
        partial void OnOFFOUTPUTSSTRUCTUREChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<bool> SWIM
        {
            get
            {
                return _SWIM;
            }
            set
            {
                OnSWIMChanging(value);
                ReportPropertyChanging("SWIM");
                _SWIM = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SWIM");
                OnSWIMChanged();
            }
        }
        private Nullable<bool> _SWIM;
        partial void OnSWIMChanging(Nullable<bool> value);
        partial void OnSWIMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<bool> BIKEOUTINGS
        {
            get
            {
                return _BIKEOUTINGS;
            }
            set
            {
                OnBIKEOUTINGSChanging(value);
                ReportPropertyChanging("BIKEOUTINGS");
                _BIKEOUTINGS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BIKEOUTINGS");
                OnBIKEOUTINGSChanged();
            }
        }
        private Nullable<bool> _BIKEOUTINGS;
        partial void OnBIKEOUTINGSChanging(Nullable<bool> value);
        partial void OnBIKEOUTINGSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<bool> BOATOUTINGS
        {
            get
            {
                return _BOATOUTINGS;
            }
            set
            {
                OnBOATOUTINGSChanging(value);
                ReportPropertyChanging("BOATOUTINGS");
                _BOATOUTINGS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BOATOUTINGS");
                OnBOATOUTINGSChanged();
            }
        }
        private Nullable<bool> _BOATOUTINGS;
        partial void OnBOATOUTINGSChanging(Nullable<bool> value);
        partial void OnBOATOUTINGSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> MEDECINEID
        {
            get
            {
                return _MEDECINEID;
            }
            set
            {
                OnMEDECINEIDChanging(value);
                ReportPropertyChanging("MEDECINEID");
                _MEDECINEID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MEDECINEID");
                OnMEDECINEIDChanged();
            }
        }
        private Nullable<int> _MEDECINEID;
        partial void OnMEDECINEIDChanging(Nullable<int> value);
        partial void OnMEDECINEIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public int ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("agsModel", "famfk", "FAMILIES")]
        public FAMILIES FAMILIES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FAMILIES>("agsModel.famfk", "FAMILIES").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FAMILIES>("agsModel.famfk", "FAMILIES").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FAMILIES> FAMILIESReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FAMILIES>("agsModel.famfk", "FAMILIES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FAMILIES>("agsModel.famfk", "FAMILIES", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="agsModel", Name="CITIES")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CITIES : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CITIES object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static CITIES CreateCITIES(int id)
        {
            CITIES cITIES = new CITIES();
            cITIES.ID = id;
            return cITIES;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public int ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string CITY
        {
            get
            {
                return _CITY;
            }
            set
            {
                OnCITYChanging(value);
                ReportPropertyChanging("CITY");
                _CITY = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CITY");
                OnCITYChanged();
            }
        }
        private string _CITY;
        partial void OnCITYChanging(string value);
        partial void OnCITYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string CP
        {
            get
            {
                return _CP;
            }
            set
            {
                OnCPChanging(value);
                ReportPropertyChanging("CP");
                _CP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CP");
                OnCPChanged();
            }
        }
        private string _CP;
        partial void OnCPChanging(string value);
        partial void OnCPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<bool> PARTNERSHIP
        {
            get
            {
                return _PARTNERSHIP;
            }
            set
            {
                OnPARTNERSHIPChanging(value);
                ReportPropertyChanging("PARTNERSHIP");
                _PARTNERSHIP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PARTNERSHIP");
                OnPARTNERSHIPChanged();
            }
        }
        private Nullable<bool> _PARTNERSHIP;
        partial void OnPARTNERSHIPChanging(Nullable<bool> value);
        partial void OnPARTNERSHIPChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("agsModel", "cityfk", "FAMILIES")]
        public EntityCollection<FAMILIES> FAMILIES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FAMILIES>("agsModel.cityfk", "FAMILIES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FAMILIES>("agsModel.cityfk", "FAMILIES", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="agsModel", Name="CIVILITIES")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CIVILITIES : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CIVILITIES object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static CIVILITIES CreateCIVILITIES(long id)
        {
            CIVILITIES cIVILITIES = new CIVILITIES();
            cIVILITIES.ID = id;
            return cIVILITIES;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public long ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string CIVILITY
        {
            get
            {
                return _CIVILITY;
            }
            set
            {
                OnCIVILITYChanging(value);
                ReportPropertyChanging("CIVILITY");
                _CIVILITY = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CIVILITY");
                OnCIVILITYChanged();
            }
        }
        private string _CIVILITY;
        partial void OnCIVILITYChanging(string value);
        partial void OnCIVILITYChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="agsModel", Name="FAMILIES")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FAMILIES : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FAMILIES object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static FAMILIES CreateFAMILIES(int id)
        {
            FAMILIES fAMILIES = new FAMILIES();
            fAMILIES.ID = id;
            return fAMILIES;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string LASTNAME
        {
            get
            {
                return _LASTNAME;
            }
            set
            {
                OnLASTNAMEChanging(value);
                ReportPropertyChanging("LASTNAME");
                _LASTNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LASTNAME");
                OnLASTNAMEChanged();
            }
        }
        private string _LASTNAME;
        partial void OnLASTNAMEChanging(string value);
        partial void OnLASTNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string FIRSTNAME
        {
            get
            {
                return _FIRSTNAME;
            }
            set
            {
                OnFIRSTNAMEChanging(value);
                ReportPropertyChanging("FIRSTNAME");
                _FIRSTNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FIRSTNAME");
                OnFIRSTNAMEChanged();
            }
        }
        private string _FIRSTNAME;
        partial void OnFIRSTNAMEChanging(string value);
        partial void OnFIRSTNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string ADRESS
        {
            get
            {
                return _ADRESS;
            }
            set
            {
                OnADRESSChanging(value);
                ReportPropertyChanging("ADRESS");
                _ADRESS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ADRESS");
                OnADRESSChanged();
            }
        }
        private string _ADRESS;
        partial void OnADRESSChanging(string value);
        partial void OnADRESSChanged();
    
        ///// <summary>
        ///// No Metadata Documentation available.
        ///// </summary>
        //[EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        //[DataMemberAttribute()]
        //public Nullable<int> CITYID
        //{
        //    get
        //    {
        //        return _CITYID;
        //    }
        //    set
        //    {
        //        OnCITYIDChanging(value);
        //        ReportPropertyChanging("CITYID");
        //        _CITYID = StructuralObject.SetValidValue(value);
        //        ReportPropertyChanged("CITYID");
        //        OnCITYIDChanged();
        //    }
        //}
        //private Nullable<int> _CITYID;
        //partial void OnCITYIDChanging(Nullable<int> value);
        //partial void OnCITYIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string TEL1
        {
            get
            {
                return _TEL1;
            }
            set
            {
                OnTEL1Changing(value);
                ReportPropertyChanging("TEL1");
                _TEL1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TEL1");
                OnTEL1Changed();
            }
        }
        private string _TEL1;
        partial void OnTEL1Changing(string value);
        partial void OnTEL1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string TEL2
        {
            get
            {
                return _TEL2;
            }
            set
            {
                OnTEL2Changing(value);
                ReportPropertyChanging("TEL2");
                _TEL2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TEL2");
                OnTEL2Changed();
            }
        }
        private string _TEL2;
        partial void OnTEL2Changing(string value);
        partial void OnTEL2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string TEL3
        {
            get
            {
                return _TEL3;
            }
            set
            {
                OnTEL3Changing(value);
                ReportPropertyChanging("TEL3");
                _TEL3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TEL3");
                OnTEL3Changed();
            }
        }
        private string _TEL3;
        partial void OnTEL3Changing(string value);
        partial void OnTEL3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public int ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> CIVILITYID
        {
            get
            {
                return _CIVILITYID;
            }
            set
            {
                OnCIVILITYIDChanging(value);
                ReportPropertyChanging("CIVILITYID");
                _CIVILITYID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CIVILITYID");
                OnCIVILITYIDChanged();
            }
        }
        private Nullable<int> _CIVILITYID;
        partial void OnCIVILITYIDChanging(Nullable<int> value);
        partial void OnCIVILITYIDChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("agsModel", "famfk", "CHILDRENS")]
        public EntityCollection<CHILDRENS> CHILDRENS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CHILDRENS>("agsModel.famfk", "CHILDRENS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CHILDRENS>("agsModel.famfk", "CHILDRENS", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("agsModel", "cityfk", "CITIES")]
        public CITIES CITIES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CITIES>("agsModel.cityfk", "CITIES").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CITIES>("agsModel.cityfk", "CITIES").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CITIES> CITIESReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CITIES>("agsModel.cityfk", "CITIES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CITIES>("agsModel.cityfk", "CITIES", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("agsModel", "familyfk", "FAMILYQUOTIENTS")]
        public EntityCollection<FAMILYQUOTIENTS> FAMILYQUOTIENTS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FAMILYQUOTIENTS>("agsModel.familyfk", "FAMILYQUOTIENTS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FAMILYQUOTIENTS>("agsModel.familyfk", "FAMILYQUOTIENTS", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="agsModel", Name="FAMILYQUOTIENTS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FAMILYQUOTIENTS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FAMILYQUOTIENTS object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static FAMILYQUOTIENTS CreateFAMILYQUOTIENTS(long id)
        {
            FAMILYQUOTIENTS fAMILYQUOTIENTS = new FAMILYQUOTIENTS();
            fAMILYQUOTIENTS.ID = id;
            return fAMILYQUOTIENTS;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public long ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private long _ID;
        partial void OnIDChanging(long value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> YEAR
        {
            get
            {
                return _YEAR;
            }
            set
            {
                OnYEARChanging(value);
                ReportPropertyChanging("YEAR");
                _YEAR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("YEAR");
                OnYEARChanged();
            }
        }
        private Nullable<int> _YEAR;
        partial void OnYEARChanging(Nullable<int> value);
        partial void OnYEARChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<int> FAMILYID
        {
            get
            {
                return _FAMILYID;
            }
            set
            {
                OnFAMILYIDChanging(value);
                ReportPropertyChanging("FAMILYID");
                _FAMILYID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FAMILYID");
                OnFAMILYIDChanged();
            }
        }
        private Nullable<int> _FAMILYID;
        partial void OnFAMILYIDChanging(Nullable<int> value);
        partial void OnFAMILYIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<float> FAMILYQUOTIENT
        {
            get
            {
                return _FAMILYQUOTIENT;
            }
            set
            {
                OnFAMILYQUOTIENTChanging(value);
                ReportPropertyChanging("FAMILYQUOTIENT");
                _FAMILYQUOTIENT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FAMILYQUOTIENT");
                OnFAMILYQUOTIENTChanged();
            }
        }
        private Nullable<float> _FAMILYQUOTIENT;
        partial void OnFAMILYQUOTIENTChanging(Nullable<float> value);
        partial void OnFAMILYQUOTIENTChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("agsModel", "familyfk", "FAMILIES")]
        public FAMILIES FAMILIES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FAMILIES>("agsModel.familyfk", "FAMILIES").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FAMILIES>("agsModel.familyfk", "FAMILIES").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FAMILIES> FAMILIESReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FAMILIES>("agsModel.familyfk", "FAMILIES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FAMILIES>("agsModel.familyfk", "FAMILIES", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="agsModel", Name="MEDECINS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MEDECINS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MEDECINS object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static MEDECINS CreateMEDECINS(int id)
        {
            MEDECINS mEDECINS = new MEDECINS();
            mEDECINS.ID = id;
            return mEDECINS;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public int ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string FULLNAME
        {
            get
            {
                return _FULLNAME;
            }
            set
            {
                OnFULLNAMEChanging(value);
                ReportPropertyChanging("FULLNAME");
                _FULLNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FULLNAME");
                OnFULLNAMEChanged();
            }
        }
        private string _FULLNAME;
        partial void OnFULLNAMEChanging(string value);
        partial void OnFULLNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public string TEL
        {
            get
            {
                return _TEL;
            }
            set
            {
                OnTELChanging(value);
                ReportPropertyChanging("TEL");
                _TEL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TEL");
                OnTELChanged();
            }
        }
        private string _TEL;
        partial void OnTELChanging(string value);
        partial void OnTELChanged();

        #endregion

    }

    #endregion

}
