//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Métadonnées de relation EDM

[assembly: EdmRelationshipAttribute("agsModel", "familyfk", "FAMILIES", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WpfMvvmApplication1.Models.FAMILIES), "CHILDRENS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WpfMvvmApplication1.Models.CHILDRENS), true)]
[assembly: EdmRelationshipAttribute("agsModel", "medecinefk", "MEDECINES", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WpfMvvmApplication1.Models.MEDECINES), "CHILDRENS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WpfMvvmApplication1.Models.CHILDRENS), true)]
[assembly: EdmRelationshipAttribute("agsModel", "cityfk", "CITIES", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WpfMvvmApplication1.Models.CITIES), "FAMILIES", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WpfMvvmApplication1.Models.FAMILIES), true)]
[assembly: EdmRelationshipAttribute("agsModel", "civilityfk", "CIVILITIES", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WpfMvvmApplication1.Models.CIVILITIES), "FAMILIES", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WpfMvvmApplication1.Models.FAMILIES), true)]
[assembly: EdmRelationshipAttribute("agsModel", "familyfk1", "FAMILIES", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WpfMvvmApplication1.Models.FAMILIES), "FAMILYQUOTIENTS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WpfMvvmApplication1.Models.FAMILYQUOTIENTS), true)]

#endregion

namespace WpfMvvmApplication1.Models
{
    #region Contextes
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    public partial class agsEntities : ObjectContext
    {
        #region Constructeurs
    
        /// <summary>
        /// Initialise un nouvel objet agsEntities à l'aide de la chaîne de connexion trouvée dans la section 'agsEntities' du fichier de configuration d'application.
        /// </summary>
        public agsEntities() : base("name=agsEntities", "agsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet agsEntities.
        /// </summary>
        public agsEntities(string connectionString) : base(connectionString, "agsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialisez un nouvel objet agsEntities.
        /// </summary>
        public agsEntities(EntityConnection connection) : base(connection, "agsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        #endregion
    
        #region Méthodes partielles
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriétés ObjectSet
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<CHILDRENS> CHILDRENS
        {
            get
            {
                if ((_CHILDRENS == null))
                {
                    _CHILDRENS = base.CreateObjectSet<CHILDRENS>("CHILDRENS");
                }
                return _CHILDRENS;
            }
        }
        private ObjectSet<CHILDRENS> _CHILDRENS;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<CITIES> CITIES
        {
            get
            {
                if ((_CITIES == null))
                {
                    _CITIES = base.CreateObjectSet<CITIES>("CITIES");
                }
                return _CITIES;
            }
        }
        private ObjectSet<CITIES> _CITIES;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<CIVILITIES> CIVILITIES
        {
            get
            {
                if ((_CIVILITIES == null))
                {
                    _CIVILITIES = base.CreateObjectSet<CIVILITIES>("CIVILITIES");
                }
                return _CIVILITIES;
            }
        }
        private ObjectSet<CIVILITIES> _CIVILITIES;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<FAMILIES> FAMILIES
        {
            get
            {
                if ((_FAMILIES == null))
                {
                    _FAMILIES = base.CreateObjectSet<FAMILIES>("FAMILIES");
                }
                return _FAMILIES;
            }
        }
        private ObjectSet<FAMILIES> _FAMILIES;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<FAMILYQUOTIENTS> FAMILYQUOTIENTS
        {
            get
            {
                if ((_FAMILYQUOTIENTS == null))
                {
                    _FAMILYQUOTIENTS = base.CreateObjectSet<FAMILYQUOTIENTS>("FAMILYQUOTIENTS");
                }
                return _FAMILYQUOTIENTS;
            }
        }
        private ObjectSet<FAMILYQUOTIENTS> _FAMILYQUOTIENTS;
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        public ObjectSet<MEDECINES> MEDECINES
        {
            get
            {
                if ((_MEDECINES == null))
                {
                    _MEDECINES = base.CreateObjectSet<MEDECINES>("MEDECINES");
                }
                return _MEDECINES;
            }
        }
        private ObjectSet<MEDECINES> _MEDECINES;

        #endregion

        #region Méthodes AddTo
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet CHILDRENS. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToCHILDRENS(CHILDRENS cHILDRENS)
        {
            base.AddObject("CHILDRENS", cHILDRENS);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet CITIES. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToCITIES(CITIES cITIES)
        {
            base.AddObject("CITIES", cITIES);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet CIVILITIES. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToCIVILITIES(CIVILITIES cIVILITIES)
        {
            base.AddObject("CIVILITIES", cIVILITIES);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet FAMILIES. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToFAMILIES(FAMILIES fAMILIES)
        {
            base.AddObject("FAMILIES", fAMILIES);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet FAMILYQUOTIENTS. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToFAMILYQUOTIENTS(FAMILYQUOTIENTS fAMILYQUOTIENTS)
        {
            base.AddObject("FAMILYQUOTIENTS", fAMILYQUOTIENTS);
        }
    
        /// <summary>
        /// Méthode déconseillée pour ajouter un nouvel objet à l'EntitySet MEDECINES. Utilisez la méthode .Add de la propriété ObjectSet&lt;T&gt; associée à la place.
        /// </summary>
        public void AddToMEDECINES(MEDECINES mEDECINES)
        {
            base.AddObject("MEDECINES", mEDECINES);
        }

        #endregion

    }

    #endregion

    #region Entités
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="agsModel", Name="CHILDRENS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CHILDRENS : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet CHILDRENS.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété ID.</param>
        /// <param name="eMT">Valeur initiale de la propriété EMT.</param>
        /// <param name="hOSPITAL">Valeur initiale de la propriété HOSPITAL.</param>
        /// <param name="cLINIC">Valeur initiale de la propriété CLINIC.</param>
        /// <param name="bEPHOTOGRAPHY">Valeur initiale de la propriété BEPHOTOGRAPHY.</param>
        /// <param name="pUBLICATIONPHOTOGRAPHY">Valeur initiale de la propriété PUBLICATIONPHOTOGRAPHY.</param>
        /// <param name="oFFOUTPUTSSTRUCTURE">Valeur initiale de la propriété OFFOUTPUTSSTRUCTURE.</param>
        /// <param name="sWIM">Valeur initiale de la propriété SWIM.</param>
        /// <param name="bIKEOUTINGS">Valeur initiale de la propriété BIKEOUTINGS.</param>
        /// <param name="bOATOUTINGS">Valeur initiale de la propriété BOATOUTINGS.</param>
        /// <param name="wITHOUTGLUTEN">Valeur initiale de la propriété WITHOUTGLUTEN.</param>
        /// <param name="wITHOUTEGG">Valeur initiale de la propriété WITHOUTEGG.</param>
        /// <param name="wITHOUTFISH">Valeur initiale de la propriété WITHOUTFISH.</param>
        /// <param name="wITHOUTPORK">Valeur initiale de la propriété WITHOUTPORK.</param>
        /// <param name="wITHOUTMEAT">Valeur initiale de la propriété WITHOUTMEAT.</param>
        public static CHILDRENS CreateCHILDRENS(global::System.Int32 id, global::System.Boolean eMT, global::System.Boolean hOSPITAL, global::System.Boolean cLINIC, global::System.Boolean bEPHOTOGRAPHY, global::System.Boolean pUBLICATIONPHOTOGRAPHY, global::System.Boolean oFFOUTPUTSSTRUCTURE, global::System.Boolean sWIM, global::System.Boolean bIKEOUTINGS, global::System.Boolean bOATOUTINGS, global::System.Boolean wITHOUTGLUTEN, global::System.Boolean wITHOUTEGG, global::System.Boolean wITHOUTFISH, global::System.Boolean wITHOUTPORK, global::System.Boolean wITHOUTMEAT)
        {
            CHILDRENS cHILDRENS = new CHILDRENS();
            cHILDRENS.ID = id;
            cHILDRENS.EMT = eMT;
            cHILDRENS.HOSPITAL = hOSPITAL;
            cHILDRENS.CLINIC = cLINIC;
            cHILDRENS.BEPHOTOGRAPHY = bEPHOTOGRAPHY;
            cHILDRENS.PUBLICATIONPHOTOGRAPHY = pUBLICATIONPHOTOGRAPHY;
            cHILDRENS.OFFOUTPUTSSTRUCTURE = oFFOUTPUTSSTRUCTURE;
            cHILDRENS.SWIM = sWIM;
            cHILDRENS.BIKEOUTINGS = bIKEOUTINGS;
            cHILDRENS.BOATOUTINGS = bOATOUTINGS;
            cHILDRENS.WITHOUTGLUTEN = wITHOUTGLUTEN;
            cHILDRENS.WITHOUTEGG = wITHOUTEGG;
            cHILDRENS.WITHOUTFISH = wITHOUTFISH;
            cHILDRENS.WITHOUTPORK = wITHOUTPORK;
            cHILDRENS.WITHOUTMEAT = wITHOUTMEAT;
            return cHILDRENS;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LASTNAME
        {
            get
            {
                return _LASTNAME;
            }
            set
            {
                OnLASTNAMEChanging(value);
                ReportPropertyChanging("LASTNAME");
                _LASTNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LASTNAME");
                OnLASTNAMEChanged();
            }
        }
        private global::System.String _LASTNAME;
        partial void OnLASTNAMEChanging(global::System.String value);
        partial void OnLASTNAMEChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FIRSTNAME
        {
            get
            {
                return _FIRSTNAME;
            }
            set
            {
                OnFIRSTNAMEChanging(value);
                ReportPropertyChanging("FIRSTNAME");
                _FIRSTNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FIRSTNAME");
                OnFIRSTNAMEChanged();
            }
        }
        private global::System.String _FIRSTNAME;
        partial void OnFIRSTNAMEChanging(global::System.String value);
        partial void OnFIRSTNAMEChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> BIRTHDATE
        {
            get
            {
                return _BIRTHDATE;
            }
            set
            {
                OnBIRTHDATEChanging(value);
                ReportPropertyChanging("BIRTHDATE");
                _BIRTHDATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BIRTHDATE");
                OnBIRTHDATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _BIRTHDATE;
        partial void OnBIRTHDATEChanging(Nullable<global::System.DateTime> value);
        partial void OnBIRTHDATEChanged();
    
        ///// <summary>
        ///// Aucune documentation sur les métadonnées n'est disponible.
        ///// </summary>
        //[EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        //[DataMemberAttribute()]
        //public Nullable<global::System.Int32> FAMILYID
        //{
        //    get
        //    {
        //        return _FAMILYID;
        //    }
        //    set
        //    {
        //        OnFAMILYIDChanging(value);
        //        ReportPropertyChanging("FAMILYID");
        //        _FAMILYID = StructuralObject.SetValidValue(value);
        //        ReportPropertyChanged("FAMILYID");
        //        OnFAMILYIDChanged();
        //    }
        //}
        //private Nullable<global::System.Int32> _FAMILYID;
        //partial void OnFAMILYIDChanging(Nullable<global::System.Int32> value);
        //partial void OnFAMILYIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> GENDERID
        {
            get
            {
                return _GENDERID;
            }
            set
            {
                OnGENDERIDChanging(value);
                ReportPropertyChanging("GENDERID");
                _GENDERID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GENDERID");
                OnGENDERIDChanged();
            }
        }
        private Nullable<global::System.Int32> _GENDERID;
        partial void OnGENDERIDChanging(Nullable<global::System.Int32> value);
        partial void OnGENDERIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean EMT
        {
            get
            {
                return _EMT;
            }
            set
            {
                OnEMTChanging(value);
                ReportPropertyChanging("EMT");
                _EMT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EMT");
                OnEMTChanged();
            }
        }
        private global::System.Boolean _EMT;
        partial void OnEMTChanging(global::System.Boolean value);
        partial void OnEMTChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean HOSPITAL
        {
            get
            {
                return _HOSPITAL;
            }
            set
            {
                OnHOSPITALChanging(value);
                ReportPropertyChanging("HOSPITAL");
                _HOSPITAL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HOSPITAL");
                OnHOSPITALChanged();
            }
        }
        private global::System.Boolean _HOSPITAL;
        partial void OnHOSPITALChanging(global::System.Boolean value);
        partial void OnHOSPITALChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean CLINIC
        {
            get
            {
                return _CLINIC;
            }
            set
            {
                OnCLINICChanging(value);
                ReportPropertyChanging("CLINIC");
                _CLINIC = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CLINIC");
                OnCLINICChanged();
            }
        }
        private global::System.Boolean _CLINIC;
        partial void OnCLINICChanging(global::System.Boolean value);
        partial void OnCLINICChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean BEPHOTOGRAPHY
        {
            get
            {
                return _BEPHOTOGRAPHY;
            }
            set
            {
                OnBEPHOTOGRAPHYChanging(value);
                ReportPropertyChanging("BEPHOTOGRAPHY");
                _BEPHOTOGRAPHY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BEPHOTOGRAPHY");
                OnBEPHOTOGRAPHYChanged();
            }
        }
        private global::System.Boolean _BEPHOTOGRAPHY;
        partial void OnBEPHOTOGRAPHYChanging(global::System.Boolean value);
        partial void OnBEPHOTOGRAPHYChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean PUBLICATIONPHOTOGRAPHY
        {
            get
            {
                return _PUBLICATIONPHOTOGRAPHY;
            }
            set
            {
                OnPUBLICATIONPHOTOGRAPHYChanging(value);
                ReportPropertyChanging("PUBLICATIONPHOTOGRAPHY");
                _PUBLICATIONPHOTOGRAPHY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PUBLICATIONPHOTOGRAPHY");
                OnPUBLICATIONPHOTOGRAPHYChanged();
            }
        }
        private global::System.Boolean _PUBLICATIONPHOTOGRAPHY;
        partial void OnPUBLICATIONPHOTOGRAPHYChanging(global::System.Boolean value);
        partial void OnPUBLICATIONPHOTOGRAPHYChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean OFFOUTPUTSSTRUCTURE
        {
            get
            {
                return _OFFOUTPUTSSTRUCTURE;
            }
            set
            {
                OnOFFOUTPUTSSTRUCTUREChanging(value);
                ReportPropertyChanging("OFFOUTPUTSSTRUCTURE");
                _OFFOUTPUTSSTRUCTURE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OFFOUTPUTSSTRUCTURE");
                OnOFFOUTPUTSSTRUCTUREChanged();
            }
        }
        private global::System.Boolean _OFFOUTPUTSSTRUCTURE;
        partial void OnOFFOUTPUTSSTRUCTUREChanging(global::System.Boolean value);
        partial void OnOFFOUTPUTSSTRUCTUREChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean SWIM
        {
            get
            {
                return _SWIM;
            }
            set
            {
                OnSWIMChanging(value);
                ReportPropertyChanging("SWIM");
                _SWIM = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SWIM");
                OnSWIMChanged();
            }
        }
        private global::System.Boolean _SWIM;
        partial void OnSWIMChanging(global::System.Boolean value);
        partial void OnSWIMChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean BIKEOUTINGS
        {
            get
            {
                return _BIKEOUTINGS;
            }
            set
            {
                OnBIKEOUTINGSChanging(value);
                ReportPropertyChanging("BIKEOUTINGS");
                _BIKEOUTINGS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BIKEOUTINGS");
                OnBIKEOUTINGSChanged();
            }
        }
        private global::System.Boolean _BIKEOUTINGS;
        partial void OnBIKEOUTINGSChanging(global::System.Boolean value);
        partial void OnBIKEOUTINGSChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean BOATOUTINGS
        {
            get
            {
                return _BOATOUTINGS;
            }
            set
            {
                OnBOATOUTINGSChanging(value);
                ReportPropertyChanging("BOATOUTINGS");
                _BOATOUTINGS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BOATOUTINGS");
                OnBOATOUTINGSChanged();
            }
        }
        private global::System.Boolean _BOATOUTINGS;
        partial void OnBOATOUTINGSChanging(global::System.Boolean value);
        partial void OnBOATOUTINGSChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MEDECINEID
        {
            get
            {
                return _MEDECINEID;
            }
            set
            {
                OnMEDECINEIDChanging(value);
                ReportPropertyChanging("MEDECINEID");
                _MEDECINEID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MEDECINEID");
                OnMEDECINEIDChanged();
            }
        }
        private Nullable<global::System.Int32> _MEDECINEID;
        partial void OnMEDECINEIDChanging(Nullable<global::System.Int32> value);
        partial void OnMEDECINEIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ALLERGIES
        {
            get
            {
                return _ALLERGIES;
            }
            set
            {
                OnALLERGIESChanging(value);
                ReportPropertyChanging("ALLERGIES");
                _ALLERGIES = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ALLERGIES");
                OnALLERGIESChanged();
            }
        }
        private global::System.String _ALLERGIES;
        partial void OnALLERGIESChanging(global::System.String value);
        partial void OnALLERGIESChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean WITHOUTGLUTEN
        {
            get
            {
                return _WITHOUTGLUTEN;
            }
            set
            {
                OnWITHOUTGLUTENChanging(value);
                ReportPropertyChanging("WITHOUTGLUTEN");
                _WITHOUTGLUTEN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WITHOUTGLUTEN");
                OnWITHOUTGLUTENChanged();
            }
        }
        private global::System.Boolean _WITHOUTGLUTEN;
        partial void OnWITHOUTGLUTENChanging(global::System.Boolean value);
        partial void OnWITHOUTGLUTENChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean WITHOUTEGG
        {
            get
            {
                return _WITHOUTEGG;
            }
            set
            {
                OnWITHOUTEGGChanging(value);
                ReportPropertyChanging("WITHOUTEGG");
                _WITHOUTEGG = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WITHOUTEGG");
                OnWITHOUTEGGChanged();
            }
        }
        private global::System.Boolean _WITHOUTEGG;
        partial void OnWITHOUTEGGChanging(global::System.Boolean value);
        partial void OnWITHOUTEGGChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean WITHOUTFISH
        {
            get
            {
                return _WITHOUTFISH;
            }
            set
            {
                OnWITHOUTFISHChanging(value);
                ReportPropertyChanging("WITHOUTFISH");
                _WITHOUTFISH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WITHOUTFISH");
                OnWITHOUTFISHChanged();
            }
        }
        private global::System.Boolean _WITHOUTFISH;
        partial void OnWITHOUTFISHChanging(global::System.Boolean value);
        partial void OnWITHOUTFISHChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean WITHOUTPORK
        {
            get
            {
                return _WITHOUTPORK;
            }
            set
            {
                OnWITHOUTPORKChanging(value);
                ReportPropertyChanging("WITHOUTPORK");
                _WITHOUTPORK = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WITHOUTPORK");
                OnWITHOUTPORKChanged();
            }
        }
        private global::System.Boolean _WITHOUTPORK;
        partial void OnWITHOUTPORKChanging(global::System.Boolean value);
        partial void OnWITHOUTPORKChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean WITHOUTMEAT
        {
            get
            {
                return _WITHOUTMEAT;
            }
            set
            {
                OnWITHOUTMEATChanging(value);
                ReportPropertyChanging("WITHOUTMEAT");
                _WITHOUTMEAT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WITHOUTMEAT");
                OnWITHOUTMEATChanged();
            }
        }
        private global::System.Boolean _WITHOUTMEAT;
        partial void OnWITHOUTMEATChanging(global::System.Boolean value);
        partial void OnWITHOUTMEATChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SPECIALARRANGEMENTS
        {
            get
            {
                return _SPECIALARRANGEMENTS;
            }
            set
            {
                OnSPECIALARRANGEMENTSChanging(value);
                ReportPropertyChanging("SPECIALARRANGEMENTS");
                _SPECIALARRANGEMENTS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SPECIALARRANGEMENTS");
                OnSPECIALARRANGEMENTSChanged();
            }
        }
        private global::System.String _SPECIALARRANGEMENTS;
        partial void OnSPECIALARRANGEMENTSChanging(global::System.String value);
        partial void OnSPECIALARRANGEMENTSChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("agsModel", "familyfk", "FAMILIES")]
        public FAMILIES FAMILIES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FAMILIES>("agsModel.familyfk", "FAMILIES").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FAMILIES>("agsModel.familyfk", "FAMILIES").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FAMILIES> FAMILIESReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FAMILIES>("agsModel.familyfk", "FAMILIES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FAMILIES>("agsModel.familyfk", "FAMILIES", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("agsModel", "medecinefk", "MEDECINES")]
        public MEDECINES MEDECINES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MEDECINES>("agsModel.medecinefk", "MEDECINES").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MEDECINES>("agsModel.medecinefk", "MEDECINES").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<MEDECINES> MEDECINESReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<MEDECINES>("agsModel.medecinefk", "MEDECINES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<MEDECINES>("agsModel.medecinefk", "MEDECINES", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="agsModel", Name="CITIES")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CITIES : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet CITIES.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété ID.</param>
        public static CITIES CreateCITIES(global::System.Int32 id)
        {
            CITIES cITIES = new CITIES();
            cITIES.ID = id;
            return cITIES;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CITY
        {
            get
            {
                return _CITY;
            }
            set
            {
                OnCITYChanging(value);
                ReportPropertyChanging("CITY");
                _CITY = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CITY");
                OnCITYChanged();
            }
        }
        private global::System.String _CITY;
        partial void OnCITYChanging(global::System.String value);
        partial void OnCITYChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CP
        {
            get
            {
                return _CP;
            }
            set
            {
                OnCPChanging(value);
                ReportPropertyChanging("CP");
                _CP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CP");
                OnCPChanged();
            }
        }
        private global::System.String _CP;
        partial void OnCPChanging(global::System.String value);
        partial void OnCPChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> PARTNERSHIP
        {
            get
            {
                return _PARTNERSHIP;
            }
            set
            {
                OnPARTNERSHIPChanging(value);
                ReportPropertyChanging("PARTNERSHIP");
                _PARTNERSHIP = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PARTNERSHIP");
                OnPARTNERSHIPChanged();
            }
        }
        private Nullable<global::System.Boolean> _PARTNERSHIP;
        partial void OnPARTNERSHIPChanging(Nullable<global::System.Boolean> value);
        partial void OnPARTNERSHIPChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("agsModel", "cityfk", "FAMILIES")]
        public EntityCollection<FAMILIES> FAMILIES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FAMILIES>("agsModel.cityfk", "FAMILIES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FAMILIES>("agsModel.cityfk", "FAMILIES", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="agsModel", Name="CIVILITIES")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CIVILITIES : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet CIVILITIES.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété ID.</param>
        public static CIVILITIES CreateCIVILITIES(global::System.Int32 id)
        {
            CIVILITIES cIVILITIES = new CIVILITIES();
            cIVILITIES.ID = id;
            return cIVILITIES;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CIVILITY
        {
            get
            {
                return _CIVILITY;
            }
            set
            {
                OnCIVILITYChanging(value);
                ReportPropertyChanging("CIVILITY");
                _CIVILITY = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CIVILITY");
                OnCIVILITYChanged();
            }
        }
        private global::System.String _CIVILITY;
        partial void OnCIVILITYChanging(global::System.String value);
        partial void OnCIVILITYChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("agsModel", "civilityfk", "FAMILIES")]
        public EntityCollection<FAMILIES> FAMILIES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FAMILIES>("agsModel.civilityfk", "FAMILIES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FAMILIES>("agsModel.civilityfk", "FAMILIES", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="agsModel", Name="FAMILIES")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FAMILIES : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet FAMILIES.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété ID.</param>
        public static FAMILIES CreateFAMILIES(global::System.Int32 id)
        {
            FAMILIES fAMILIES = new FAMILIES();
            fAMILIES.ID = id;
            return fAMILIES;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CIVILITYID
        {
            get
            {
                return _CIVILITYID;
            }
            set
            {
                OnCIVILITYIDChanging(value);
                ReportPropertyChanging("CIVILITYID");
                _CIVILITYID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CIVILITYID");
                OnCIVILITYIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CIVILITYID;
        partial void OnCIVILITYIDChanging(Nullable<global::System.Int32> value);
        partial void OnCIVILITYIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LASTNAME
        {
            get
            {
                return _LASTNAME;
            }
            set
            {
                OnLASTNAMEChanging(value);
                ReportPropertyChanging("LASTNAME");
                _LASTNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LASTNAME");
                OnLASTNAMEChanged();
            }
        }
        private global::System.String _LASTNAME;
        partial void OnLASTNAMEChanging(global::System.String value);
        partial void OnLASTNAMEChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FIRSTNAME
        {
            get
            {
                return _FIRSTNAME;
            }
            set
            {
                OnFIRSTNAMEChanging(value);
                ReportPropertyChanging("FIRSTNAME");
                _FIRSTNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FIRSTNAME");
                OnFIRSTNAMEChanged();
            }
        }
        private global::System.String _FIRSTNAME;
        partial void OnFIRSTNAMEChanging(global::System.String value);
        partial void OnFIRSTNAMEChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ADDRESS
        {
            get
            {
                return _ADDRESS;
            }
            set
            {
                OnADDRESSChanging(value);
                ReportPropertyChanging("ADDRESS");
                _ADDRESS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ADDRESS");
                OnADDRESSChanged();
            }
        }
        private global::System.String _ADDRESS;
        partial void OnADDRESSChanging(global::System.String value);
        partial void OnADDRESSChanged();
    
        ///// <summary>
        ///// Aucune documentation sur les métadonnées n'est disponible.
        ///// </summary>
        //[EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        //[DataMemberAttribute()]
        //public Nullable<global::System.Int32> CITYID
        //{
        //    get
        //    {
        //        return _CITYID;
        //    }
        //    set
        //    {
        //        OnCITYIDChanging(value);
        //        ReportPropertyChanging("CITYID");
        //        _CITYID = StructuralObject.SetValidValue(value);
        //        ReportPropertyChanged("CITYID");
        //        OnCITYIDChanged();
        //    }
        //}
        //private Nullable<global::System.Int32> _CITYID;
        //partial void OnCITYIDChanging(Nullable<global::System.Int32> value);
        //partial void OnCITYIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TEL1
        {
            get
            {
                return _TEL1;
            }
            set
            {
                OnTEL1Changing(value);
                ReportPropertyChanging("TEL1");
                _TEL1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TEL1");
                OnTEL1Changed();
            }
        }
        private global::System.String _TEL1;
        partial void OnTEL1Changing(global::System.String value);
        partial void OnTEL1Changed();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TEL2
        {
            get
            {
                return _TEL2;
            }
            set
            {
                OnTEL2Changing(value);
                ReportPropertyChanging("TEL2");
                _TEL2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TEL2");
                OnTEL2Changed();
            }
        }
        private global::System.String _TEL2;
        partial void OnTEL2Changing(global::System.String value);
        partial void OnTEL2Changed();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TEL3
        {
            get
            {
                return _TEL3;
            }
            set
            {
                OnTEL3Changing(value);
                ReportPropertyChanging("TEL3");
                _TEL3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TEL3");
                OnTEL3Changed();
            }
        }
        private global::System.String _TEL3;
        partial void OnTEL3Changing(global::System.String value);
        partial void OnTEL3Changed();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EMAIL
        {
            get
            {
                return _EMAIL;
            }
            set
            {
                OnEMAILChanging(value);
                ReportPropertyChanging("EMAIL");
                _EMAIL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EMAIL");
                OnEMAILChanged();
            }
        }
        private global::System.String _EMAIL;
        partial void OnEMAILChanging(global::System.String value);
        partial void OnEMAILChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PARTNERCIVILITYID
        {
            get
            {
                return _PARTNERCIVILITYID;
            }
            set
            {
                OnPARTNERCIVILITYIDChanging(value);
                ReportPropertyChanging("PARTNERCIVILITYID");
                _PARTNERCIVILITYID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PARTNERCIVILITYID");
                OnPARTNERCIVILITYIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PARTNERCIVILITYID;
        partial void OnPARTNERCIVILITYIDChanging(Nullable<global::System.Int32> value);
        partial void OnPARTNERCIVILITYIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PARTNERLASTNAME
        {
            get
            {
                return _PARTNERLASTNAME;
            }
            set
            {
                OnPARTNERLASTNAMEChanging(value);
                ReportPropertyChanging("PARTNERLASTNAME");
                _PARTNERLASTNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PARTNERLASTNAME");
                OnPARTNERLASTNAMEChanged();
            }
        }
        private global::System.String _PARTNERLASTNAME;
        partial void OnPARTNERLASTNAMEChanging(global::System.String value);
        partial void OnPARTNERLASTNAMEChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PARTNERFIRSTNAME
        {
            get
            {
                return _PARTNERFIRSTNAME;
            }
            set
            {
                OnPARTNERFIRSTNAMEChanging(value);
                ReportPropertyChanging("PARTNERFIRSTNAME");
                _PARTNERFIRSTNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PARTNERFIRSTNAME");
                OnPARTNERFIRSTNAMEChanged();
            }
        }
        private global::System.String _PARTNERFIRSTNAME;
        partial void OnPARTNERFIRSTNAMEChanging(global::System.String value);
        partial void OnPARTNERFIRSTNAMEChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PARTNERADDRESS
        {
            get
            {
                return _PARTNERADDRESS;
            }
            set
            {
                OnPARTNERADDRESSChanging(value);
                ReportPropertyChanging("PARTNERADDRESS");
                _PARTNERADDRESS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PARTNERADDRESS");
                OnPARTNERADDRESSChanged();
            }
        }
        private global::System.String _PARTNERADDRESS;
        partial void OnPARTNERADDRESSChanging(global::System.String value);
        partial void OnPARTNERADDRESSChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PARTNERCITYID
        {
            get
            {
                return _PARTNERCITYID;
            }
            set
            {
                OnPARTNERCITYIDChanging(value);
                ReportPropertyChanging("PARTNERCITYID");
                _PARTNERCITYID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PARTNERCITYID");
                OnPARTNERCITYIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PARTNERCITYID;
        partial void OnPARTNERCITYIDChanging(Nullable<global::System.Int32> value);
        partial void OnPARTNERCITYIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PARTNERTEL1
        {
            get
            {
                return _PARTNERTEL1;
            }
            set
            {
                OnPARTNERTEL1Changing(value);
                ReportPropertyChanging("PARTNERTEL1");
                _PARTNERTEL1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PARTNERTEL1");
                OnPARTNERTEL1Changed();
            }
        }
        private global::System.String _PARTNERTEL1;
        partial void OnPARTNERTEL1Changing(global::System.String value);
        partial void OnPARTNERTEL1Changed();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PARTNERTEL2
        {
            get
            {
                return _PARTNERTEL2;
            }
            set
            {
                OnPARTNERTEL2Changing(value);
                ReportPropertyChanging("PARTNERTEL2");
                _PARTNERTEL2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PARTNERTEL2");
                OnPARTNERTEL2Changed();
            }
        }
        private global::System.String _PARTNERTEL2;
        partial void OnPARTNERTEL2Changing(global::System.String value);
        partial void OnPARTNERTEL2Changed();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PARTNERTEL3
        {
            get
            {
                return _PARTNERTEL3;
            }
            set
            {
                OnPARTNERTEL3Changing(value);
                ReportPropertyChanging("PARTNERTEL3");
                _PARTNERTEL3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PARTNERTEL3");
                OnPARTNERTEL3Changed();
            }
        }
        private global::System.String _PARTNERTEL3;
        partial void OnPARTNERTEL3Changing(global::System.String value);
        partial void OnPARTNERTEL3Changed();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PARTNEREMAIL
        {
            get
            {
                return _PARTNEREMAIL;
            }
            set
            {
                OnPARTNEREMAILChanging(value);
                ReportPropertyChanging("PARTNEREMAIL");
                _PARTNEREMAIL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PARTNEREMAIL");
                OnPARTNEREMAILChanged();
            }
        }
        private global::System.String _PARTNEREMAIL;
        partial void OnPARTNEREMAILChanging(global::System.String value);
        partial void OnPARTNEREMAILChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PAYERCIVILITYID
        {
            get
            {
                return _PAYERCIVILITYID;
            }
            set
            {
                OnPAYERCIVILITYIDChanging(value);
                ReportPropertyChanging("PAYERCIVILITYID");
                _PAYERCIVILITYID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PAYERCIVILITYID");
                OnPAYERCIVILITYIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PAYERCIVILITYID;
        partial void OnPAYERCIVILITYIDChanging(Nullable<global::System.Int32> value);
        partial void OnPAYERCIVILITYIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PAYERLASTNAME
        {
            get
            {
                return _PAYERLASTNAME;
            }
            set
            {
                OnPAYERLASTNAMEChanging(value);
                ReportPropertyChanging("PAYERLASTNAME");
                _PAYERLASTNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PAYERLASTNAME");
                OnPAYERLASTNAMEChanged();
            }
        }
        private global::System.String _PAYERLASTNAME;
        partial void OnPAYERLASTNAMEChanging(global::System.String value);
        partial void OnPAYERLASTNAMEChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PAYERFIRSTNAME
        {
            get
            {
                return _PAYERFIRSTNAME;
            }
            set
            {
                OnPAYERFIRSTNAMEChanging(value);
                ReportPropertyChanging("PAYERFIRSTNAME");
                _PAYERFIRSTNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PAYERFIRSTNAME");
                OnPAYERFIRSTNAMEChanged();
            }
        }
        private global::System.String _PAYERFIRSTNAME;
        partial void OnPAYERFIRSTNAMEChanging(global::System.String value);
        partial void OnPAYERFIRSTNAMEChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PAYERADDRESS
        {
            get
            {
                return _PAYERADDRESS;
            }
            set
            {
                OnPAYERADDRESSChanging(value);
                ReportPropertyChanging("PAYERADDRESS");
                _PAYERADDRESS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PAYERADDRESS");
                OnPAYERADDRESSChanged();
            }
        }
        private global::System.String _PAYERADDRESS;
        partial void OnPAYERADDRESSChanging(global::System.String value);
        partial void OnPAYERADDRESSChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PAYERCITYID
        {
            get
            {
                return _PAYERCITYID;
            }
            set
            {
                OnPAYERCITYIDChanging(value);
                ReportPropertyChanging("PAYERCITYID");
                _PAYERCITYID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PAYERCITYID");
                OnPAYERCITYIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PAYERCITYID;
        partial void OnPAYERCITYIDChanging(Nullable<global::System.Int32> value);
        partial void OnPAYERCITYIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PAYERTEL1
        {
            get
            {
                return _PAYERTEL1;
            }
            set
            {
                OnPAYERTEL1Changing(value);
                ReportPropertyChanging("PAYERTEL1");
                _PAYERTEL1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PAYERTEL1");
                OnPAYERTEL1Changed();
            }
        }
        private global::System.String _PAYERTEL1;
        partial void OnPAYERTEL1Changing(global::System.String value);
        partial void OnPAYERTEL1Changed();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PAYERTEL2
        {
            get
            {
                return _PAYERTEL2;
            }
            set
            {
                OnPAYERTEL2Changing(value);
                ReportPropertyChanging("PAYERTEL2");
                _PAYERTEL2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PAYERTEL2");
                OnPAYERTEL2Changed();
            }
        }
        private global::System.String _PAYERTEL2;
        partial void OnPAYERTEL2Changing(global::System.String value);
        partial void OnPAYERTEL2Changed();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PAYERTEL3
        {
            get
            {
                return _PAYERTEL3;
            }
            set
            {
                OnPAYERTEL3Changing(value);
                ReportPropertyChanging("PAYERTEL3");
                _PAYERTEL3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PAYERTEL3");
                OnPAYERTEL3Changed();
            }
        }
        private global::System.String _PAYERTEL3;
        partial void OnPAYERTEL3Changing(global::System.String value);
        partial void OnPAYERTEL3Changed();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PAYEREMAIL
        {
            get
            {
                return _PAYEREMAIL;
            }
            set
            {
                OnPAYEREMAILChanging(value);
                ReportPropertyChanging("PAYEREMAIL");
                _PAYEREMAIL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PAYEREMAIL");
                OnPAYEREMAILChanged();
            }
        }
        private global::System.String _PAYEREMAIL;
        partial void OnPAYEREMAILChanging(global::System.String value);
        partial void OnPAYEREMAILChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SOCIALSECURITYID
        {
            get
            {
                return _SOCIALSECURITYID;
            }
            set
            {
                OnSOCIALSECURITYIDChanging(value);
                ReportPropertyChanging("SOCIALSECURITYID");
                _SOCIALSECURITYID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SOCIALSECURITYID");
                OnSOCIALSECURITYIDChanged();
            }
        }
        private Nullable<global::System.Int32> _SOCIALSECURITYID;
        partial void OnSOCIALSECURITYIDChanging(Nullable<global::System.Int32> value);
        partial void OnSOCIALSECURITYIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RECIPIENTNUMBER
        {
            get
            {
                return _RECIPIENTNUMBER;
            }
            set
            {
                OnRECIPIENTNUMBERChanging(value);
                ReportPropertyChanging("RECIPIENTNUMBER");
                _RECIPIENTNUMBER = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RECIPIENTNUMBER");
                OnRECIPIENTNUMBERChanged();
            }
        }
        private global::System.String _RECIPIENTNUMBER;
        partial void OnRECIPIENTNUMBERChanging(global::System.String value);
        partial void OnRECIPIENTNUMBERChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("agsModel", "familyfk", "CHILDRENS")]
        public EntityCollection<CHILDRENS> CHILDRENS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CHILDRENS>("agsModel.familyfk", "CHILDRENS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CHILDRENS>("agsModel.familyfk", "CHILDRENS", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("agsModel", "cityfk", "CITIES")]
        public CITIES CITIES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CITIES>("agsModel.cityfk", "CITIES").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CITIES>("agsModel.cityfk", "CITIES").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CITIES> CITIESReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CITIES>("agsModel.cityfk", "CITIES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CITIES>("agsModel.cityfk", "CITIES", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("agsModel", "civilityfk", "CIVILITIES")]
        public CIVILITIES CIVILITIES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CIVILITIES>("agsModel.civilityfk", "CIVILITIES").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CIVILITIES>("agsModel.civilityfk", "CIVILITIES").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CIVILITIES> CIVILITIESReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CIVILITIES>("agsModel.civilityfk", "CIVILITIES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CIVILITIES>("agsModel.civilityfk", "CIVILITIES", value);
                }
            }
        }
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("agsModel", "familyfk1", "FAMILYQUOTIENTS")]
        public EntityCollection<FAMILYQUOTIENTS> FAMILYQUOTIENTS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<FAMILYQUOTIENTS>("agsModel.familyfk1", "FAMILYQUOTIENTS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<FAMILYQUOTIENTS>("agsModel.familyfk1", "FAMILYQUOTIENTS", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="agsModel", Name="FAMILYQUOTIENTS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FAMILYQUOTIENTS : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet FAMILYQUOTIENTS.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété ID.</param>
        public static FAMILYQUOTIENTS CreateFAMILYQUOTIENTS(global::System.Int64 id)
        {
            FAMILYQUOTIENTS fAMILYQUOTIENTS = new FAMILYQUOTIENTS();
            fAMILYQUOTIENTS.ID = id;
            return fAMILYQUOTIENTS;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int64 _ID;
        partial void OnIDChanging(global::System.Int64 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> YEAR
        {
            get
            {
                return _YEAR;
            }
            set
            {
                OnYEARChanging(value);
                ReportPropertyChanging("YEAR");
                _YEAR = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("YEAR");
                OnYEARChanged();
            }
        }
        private Nullable<global::System.Int32> _YEAR;
        partial void OnYEARChanging(Nullable<global::System.Int32> value);
        partial void OnYEARChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FAMILYID
        {
            get
            {
                return _FAMILYID;
            }
            set
            {
                OnFAMILYIDChanging(value);
                ReportPropertyChanging("FAMILYID");
                _FAMILYID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FAMILYID");
                OnFAMILYIDChanged();
            }
        }
        private Nullable<global::System.Int32> _FAMILYID;
        partial void OnFAMILYIDChanging(Nullable<global::System.Int32> value);
        partial void OnFAMILYIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> FAMILYQUOTIENT
        {
            get
            {
                return _FAMILYQUOTIENT;
            }
            set
            {
                OnFAMILYQUOTIENTChanging(value);
                ReportPropertyChanging("FAMILYQUOTIENT");
                _FAMILYQUOTIENT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FAMILYQUOTIENT");
                OnFAMILYQUOTIENTChanged();
            }
        }
        private Nullable<global::System.Single> _FAMILYQUOTIENT;
        partial void OnFAMILYQUOTIENTChanging(Nullable<global::System.Single> value);
        partial void OnFAMILYQUOTIENTChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("agsModel", "familyfk1", "FAMILIES")]
        public FAMILIES FAMILIES
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FAMILIES>("agsModel.familyfk1", "FAMILIES").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FAMILIES>("agsModel.familyfk1", "FAMILIES").Value = value;
            }
        }
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<FAMILIES> FAMILIESReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<FAMILIES>("agsModel.familyfk1", "FAMILIES");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<FAMILIES>("agsModel.familyfk1", "FAMILIES", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Aucune documentation sur les métadonnées n'est disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="agsModel", Name="MEDECINES")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MEDECINES : EntityObject
    {
        #region Méthode de fabrique
    
        /// <summary>
        /// Créez un nouvel objet MEDECINES.
        /// </summary>
        /// <param name="id">Valeur initiale de la propriété ID.</param>
        public static MEDECINES CreateMEDECINES(global::System.Int32 id)
        {
            MEDECINES mEDECINES = new MEDECINES();
            mEDECINES.ID = id;
            return mEDECINES;
        }

        #endregion

        #region Propriétés primitives
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FULLNAME
        {
            get
            {
                return _FULLNAME;
            }
            set
            {
                OnFULLNAMEChanging(value);
                ReportPropertyChanging("FULLNAME");
                _FULLNAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FULLNAME");
                OnFULLNAMEChanged();
            }
        }
        private global::System.String _FULLNAME;
        partial void OnFULLNAMEChanging(global::System.String value);
        partial void OnFULLNAMEChanged();
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TEL
        {
            get
            {
                return _TEL;
            }
            set
            {
                OnTELChanging(value);
                ReportPropertyChanging("TEL");
                _TEL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TEL");
                OnTELChanged();
            }
        }
        private global::System.String _TEL;
        partial void OnTELChanging(global::System.String value);
        partial void OnTELChanged();

        #endregion

    
        #region Propriétés de navigation
    
        /// <summary>
        /// Aucune documentation sur les métadonnées n'est disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("agsModel", "medecinefk", "CHILDRENS")]
        public EntityCollection<CHILDRENS> CHILDRENS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CHILDRENS>("agsModel.medecinefk", "CHILDRENS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CHILDRENS>("agsModel.medecinefk", "CHILDRENS", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
