//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfMvvmApplication1.Models.POCO
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class FAMILYQUOTIENTS
    {
        public long ID { get; set; }
        public Nullable<int> YEAR { get; set; }
        public Nullable<int> FAMILYID { get; set; }
        public Nullable<float> FAMILYQUOTIENT { get; set; }
    
        public virtual FAMILIES FAMILIES { get; set; }
    }
}
