//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfMvvmApplication1.Models.POCO
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class FAMILIES
    {
        public FAMILIES()
        {
            this.CHILDRENS = new ObservableCollection<CHILDRENS>();
            this.FAMILYQUOTIENTS = new ObservableCollection<FAMILYQUOTIENTS>();
        }
    
        public string LASTNAME { get; set; }
        public string FIRSTNAME { get; set; }
        public string ADRESS { get; set; }
        public Nullable<int> CITYID { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string TEL3 { get; set; }
        public int ID { get; set; }
    
        public virtual ObservableCollection<CHILDRENS> CHILDRENS { get; set; }
        public virtual CITIES CITIES { get; set; }
        public virtual ObservableCollection<FAMILYQUOTIENTS> FAMILYQUOTIENTS { get; set; }
    }
}
