//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfMvvmApplication1.Models.POCO
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class MEDECINS
    {
        public int ID { get; set; }
        public string FULLNAME { get; set; }
        public string TEL { get; set; }
    }
}
