//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfMvvmApplication1.Models.POCO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class agsEntities : DbContext
    {
        public agsEntities()
            : base("name=agsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHILDRENS> CHILDRENS { get; set; }
        public virtual DbSet<CITIES> CITIES { get; set; }
        public virtual DbSet<CIVILITIES> CIVILITIES { get; set; }
        public virtual DbSet<FAMILIES> FAMILIES { get; set; }
        public virtual DbSet<FAMILYQUOTIENTS> FAMILYQUOTIENTS { get; set; }
        public virtual DbSet<MEDECINS> MEDECINS { get; set; }
    }
}
